
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" filter-color="black" data-image="../../assets/img/fundo.jpg">
		
		<div class="content">
			<div class="container">
				<div class="row">".
					<div class="col-md-10 col-sm-2 col-md-offset-1 col-sm-offset-0">
		                <div class="card">

		                    <form action="/run/decript" method="post" accept-charset="utf-8" id="crip-decript" class="form-horizontal" >
		                        

		                        <div class="card-header card-header-text" data-background-color="rose">
		                            <h4 class="card-title">Criptografar</h4>
		                        </div>

		                        <div class="card-content">
		                            
		                            <div class="row">
		                                
		                                <label class="col-sm-2 label-on-left">Digite</label>
		                                <div class="col-sm-8">
		                                    <div class="form-group label-floating is-empty">
		                                        <textarea rows="4" name="text" cols="50"></textarea>
		                                    </div>
		                                </div>  
                                    </div>

                                    <div class="col-sm-12">
                                        <h4>Saida:</h4>
                                        <h5>Cifra de Cesar : <?php echo $this->view->criptcesar;?></h5 > 
                                        <h5>AES256 com SALT : <?php echo $this->view->criptsalt;?></h5 >
                                        
                                    </div>
                  
		                        </div>
		                        <br/>
		                        <br/>
		 					

		 					<div class="form-group">
		                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
								  	<button class="btn btn-primary decript" type="submit">decript</button>

		                          	<button type="submit" class="btn btn-rose btn-fill cript">cript</button>
		                        </div>
		          			</div>

		                    </form>
		                </div>
		            </div>
				"</div>
            </div>
        </div>	            

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>
    </div>
</div>