<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" filter-color="black" data-image="../../assets/img/fundo.jpg">
		
		<div class="content">
			<div class="container">
				<div class="row">".
					<div class="col-md-10 col-sm-2 col-md-offset-1 col-sm-offset-0">
		                <div class="card">

		                    <form action="/update/<?php echo $this->view->device->id;?>/Device" method="post" accept-charset="utf-8" class="form-horizontal" >
		                        

		                        <div class="card-header card-header-text" data-background-color="rose">
		                            <h4 class="card-title">Cadastro de Dispositivo</h4>
		                        </div>

		                        <div class="card-content">

		                            <div class="row">
		                                
		                                <label class="col-sm-2 label-on-left">Hostname</label>
		                                <div class="col-sm-8">
		                                    <div class="form-group label-floating is-empty">
		                                        <input type="text" value="<?php echo $this->view->device->hostname;?>" class="form-control" name="hostname"  />
		                                    </div>
		                                </div>
		                            
		                            </div>

		                            <div class="row">

		                                <label class="col-sm-2 label-on-left">Ip</label>
		                                <div class="col-sm-8">
		                                    <div class="form-group label-floating is-empty">
		                                        <input type="text" value="<?php echo $this->view->device->ip;?>" class="form-control" name="Ip" />
		                                    </div>
		                                </div>
		                           
		                            </div>
		                        
		                            <div class="row">
		                                <label class="col-sm-2 label-on-left">Tipo</label>
		                                
		                                <div class="col-sm-8">
		                                    
		                                    <div class="form-group label-floating is-empty">
		                                        <label class="control-label"></label>
		                                        <input type="text" value="<?php echo $this->view->device->tipo;?>" class="form-control" name="tipo"/>
		                                    </div>
		                                
		                                </div>
		                            </div>


		                            <div class="row">
		                                <label class="col-sm-2 label-on-left">Fabricante</label>
		                                
		                                <div class="col-sm-8">
		                                    
		                                    <div class="form-group label-floating is-empty">
		                                        <label class="control-label"></label>
		                                        <input type="text" class="form-control" value="<?php echo $this->view->device->fabricante;?>" name="fabricante"/>
		                                    </div>
		                                
		                                </div>
		                            </div>

		                        </div>
		                        <br/>
		                        <br/>
		 					

		 					<div class="form-group">
		                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
								  	<button class="btn btn-primary" type="reset">Cancel</button>

		                          	<button type="submit" class="btn btn-rose btn-fill">Salvar</button>
		                        </div>
		          			</div>

		                    </form>
		                </div>
		            </div>
				"</div>
            </div>
        </div>		            

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>
    "</div>
</div>