<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" filter-color="black" data-image="../../assets/img/fundo.jpg">
		
		<div class="content">
			<div class="container">
				<div class="row">".
					<div class="card">
					    <div class="card-header card-header-icon" data-background-color="rose">
					        <i class="material-icons">assignment</i>
					    </div>
					    <div class="card-content">
					        <h4 class="card-title">Dispositivos</h4>
					        <div class="table-responsive">
					            <table class="table data-table">
					            	<?php echo $this->view->devices; ?>
					            </table>
					        </div>
					    </div>
					</div>
				</div>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>
    </div>
</div>
