
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" filter-color="black" data-image="../../assets/img/fundo.jpg">
		
		<div class="content">
			<div class="container">
				<div class="row">".
					<div class="col-md-10 col-sm-2 col-md-offset-1 col-sm-offset-0">
		                <div class="card">

                        <br>
                        <br>
                        
                        <div class="row">
                            
                            <label class="col-sm-2 label-on-left">Comandos</label>
                            <div class="col-sm-8">
                                <div class="form-group label-floating is-empty">
                                    <textarea rows="4" name="command" cols="50"> <?php echo $this->view->output;?></textarea>
                                </div>
                            </div>
                        
                        </div>
		                        
		                </div>
		            </div>
				"</div>
            </div>
        </div>	            

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>
    "</div>
</div>